import {
   LogoAstro,
   LogoBootstrap,
   LogoReact,
   LogoHTML,
   LogoCSS,
   LogoGit,
   LogoSass,
   LogoJS,
   LogoGsap,
   LogoFireBase,
   LogoTypeScript,
} from "./assets/Icons"

export const projectsArray = [
   {
      id: 1,
      name: "Urban Harmony Portal",
      src: "/Desktop 2026.02.19 - 16.38.38.02 - Trim.mp4",
      github: "https://github.com/Valenmetal/",
      url: "https://valenmetal.github.io/",
      logos: [
         <LogoReact />,
         <LogoTypeScript />,
         <LogoGsap />,
         <LogoSass />,
         <LogoGit />,
      ],
   },
   {
      id: 2,
      name: "Studio V-Design System",
      src: "/Desktop 2026.02.19 - 16.40.58.03 - Trim.mp4",
      github: "https://github.com/Valenmetal/",
      url: "https://valenmetal.github.io/",
      logos: [
         <LogoReact />,
         <LogoTypeScript />,
         <LogoGsap />,
         <LogoSass />,
         <LogoGit />,
      ],
   },
   {
      id: 3,
      name: "ArchiTech Solutions",
      src: "/Desktop 2026.02.19 - 16.46.04.05 - Trim.mp4",
      github: "https://github.com/Valenmetal/",
      url: "https://valenmetal.github.io/",
      logos: [
         <LogoReact />,
         <LogoTypeScript />,
         <LogoGsap />,
         <LogoSass />,
         <LogoGit />,
      ],
   },
   {
      id: 4,
      name: "Structure Flow",
      src: "/Desktop 2026.02.19 - 16.47.47.06 - Trim.mp4",
      github: "https://github.com/Valenmetal/",
      url: "https://valenmetal.github.io/",
      logos: [
         <LogoReact />,
         <LogoTypeScript />,
         <LogoGsap />,
         <LogoSass />,
         <LogoGit />,
      ],
   },
   {
      id: 5,
      name: "Minimalist Spaces",
      src: "/Desktop 2026.02.19 - 16.49.31.07 - Trim.mp4",
      github: "https://github.com/Valenmetal/",
      url: "https://valenmetal.github.io/",
      logos: [
         <LogoReact />,
         <LogoTypeScript />,
         <LogoGsap />,
         <LogoSass />,
         <LogoGit />,
      ],
   },
   {
      id: 6,
      name: "GeoMetric Dashboard",
      src: "/Desktop 2026.02.19 - 16.51.52.08 - Trim.mp4",
      github: "https://github.com/Valenmetal/",
      url: "https://valenmetal.github.io/",
      logos: [
         <LogoReact />,
         <LogoTypeScript />,
         <LogoGsap />,
         <LogoSass />,
         <LogoGit />,
      ],
   },
   {
      id: 7,
      name: "Blueprint Visualization",
      src: "/Desktop 2026.02.19 - 17.05.50.09 - Trim.mp4",
      github: "https://github.com/Valenmetal/",
      url: "https://valenmetal.github.io/",
      logos: [
         <LogoReact />,
         <LogoTypeScript />,
         <LogoGsap />,
         <LogoSass />,
         <LogoGit />,
      ],
   },
   {
      id: 8,
      name: "Bonofilms",
      src: "/bono.mp4",
      github: "https://github.com/Valenmetal/bonofilms",
      url: "https://bonofilms.com/",
      logos: [
         <LogoReact />,
         <LogoGsap />,
         <LogoSass />,
         <LogoGit />,
         <LogoHTML />,
         <LogoCSS />,
         <LogoJS />,
      ],
   },
   {
      id: 9,
      name: "Astro E-Commerce",
      src: "/astro.mp4",
      github: "https://github.com/Valenmetal/React-Astro-E-Commerce",
      url: "https://valenmetal.github.io/React-Astro-E-Commerce/",
      logos: [
         <LogoReact />,
         <LogoAstro />,
         <LogoGsap />,
         <LogoSass />,
         <LogoGit />,
         <LogoHTML />,
         <LogoCSS />,
         <LogoJS />,
      ],
   },
]
